spring.application.name=Safo_Marva_Tour
server.port=8080

# DB yo'q - faqat static sahifa
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
  org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Telegram Bot Settings
telegram.bot.token=8726481674:AAEqvxqyqLsvrN3vIuDXi-2jJRJkPVPp0sc
telegram.bot.adminId=6448561095

# Static resources
spring.web.resources.static-locations=classpath:/static/
