# Spring Datasource Configurations
spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:postgres}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:root1234}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port (Matching our landing page expectations)
server.port=${PORT:3000}

# Telegram Bot configurations
bot.token=${BOT_TOKEN:8726481674:AAEXbT4JHZ2Acs_vFBqbbQRlE7yOqn-9nb4}
bot.username=${BOT_USERNAME:safomarvawebbot}
bot.leadToken=${LEAD_BOT_TOKEN:8726481674:AAEXbT4JHZ2Acs_vFBqbbQRlE7yOqn-9nb4}
bot.admins=${TELEGRAM_ADMINS:6448561095,1809187274}

# Admin REST API Authentication Key
admin.api-key=${ADMIN_API_KEY:safo_marva_secret_admin_key_2026}

# Enable Static Content Serving (landing page html and galereya)
spring.web.resources.static-locations=classpath:/static/,file:./
